[users]
alice = "$2b$12$pDdDuYqXaP2KhmgrUppHRebe55A72hCPwVpe/jmSbchk/NxCyd3qa"
bob = "$2b$12$wrXYGtk6YRqDiIAZWP/BVORfF/kN7DFgAaqWa9xUoTRUhjZKT2gKC"
fendy = "$2b$12$0a0rcZjxS7TfrzTXWQfFr.jEgvZNuUpda6XTWufdFh7AWVJyly7SG"
insung = "$2b$12$he.k.M5QZ/GuqWkMPslpzewPYsEsHyDXfwJnqcjDPqaW2.K6HgH66"
